blueprint:
  name: Sonos Connect Sync
  description: "Sync volume and source control between Sonos Connect and the receiver it's connected to.\n\n
    Forked from [here](https://community.home-assistant.io/t/sync-sonos-connect-amp-or-port-volume-and-source-with-your-receiver/358302)."
  domain: automation
  source_url: https://github.com/Ru4rc/HomeAssistant/blob/main/Blueprints/sonos_connect_sync.yaml
  input:
    sonos_connect:
      name: Sonos Connect
      description: Select your Sonos Connect media player
      selector:
        entity:
          integration: sonos
          domain: media_player
    receiver:
      name: Receiver
      description: Select your A/V Receiver
      selector:
        entity:
          domain: media_player
    receiver_source:
      name: Receiver source name
      description: The source name of the receiver associated with your Sonos Connect.
      default: Sonos
      selector:
        text:
    auto_turn_off:
      name: Auto turn off receiver
      description: Toggle whether the receiver should turn off automatically after playback stops.
      default: false
      selector:
        boolean:
    turn_off_delay:
      name: Receiver turn off delay
      description: If set above, specify a delay before the receiver will turn off after the Sonos Connect stopped playing.
      default: 300
      selector:
        number:
          min: 0
          max: 3600
          unit_of_measurement: seconds
    sync_volume:
      name: Synchronise volume
      description: Toggle wether the volume between the Sonos Connect and the A/V Receiver should be synchronized.
      default: true
      selector:
        boolean:
    sync_volume_buffer_time:
      name: Buffer time between sync
      description: Time to wait before synchronizing the volume between devices. Helps with debouncing.
      default: 1000
      selector:
        number:
          min: 0
          max: 3000
          unit_of_measurement: milliseconds

mode: queued

variables:
  receiver_entity: !input receiver
  receiver_target_source: !input receiver_source
  receiver_current_source: >
    {{ state_attr(receiver_entity, 'source') }}
  receiver_current_volume: >
    {{ state_attr(receiver_entity, 'volume_level')|float(0) }}
  sonos_entity: !input sonos_connect
  sonos_current_volume: >
    {{ state_attr(sonos_entity, 'volume_level')|float(0) }}
  sync_volume: !input sync_volume
  auto_turn_off: !input auto_turn_off


trigger:
  - platform: state
    entity_id: !input sonos_connect
    to: playing
    id: sonos_playing

  - platform: state
    entity_id: !input sonos_connect
    from: playing
    for:
      seconds: !input turn_off_delay
    id: sonos_paused

  - platform: state
    entity_id: !input receiver
    attribute: source
    from: !input receiver_source 
    id: receiver_source_changed

  - platform: state
    entity_id: !input sonos_connect
    attribute: volume_level
    for:
      milliseconds: !input sync_volume_buffer_time
    id: sonos_volume

  - platform: state
    entity_id: !input receiver
    attribute: volume_level
    for:
      milliseconds: !input sync_volume_buffer_time
    id: receiver_volume

action:
  - choose:
    - alias: "Switch receiver source"
      conditions:
        - condition: trigger
          id: sonos_playing
        - condition: template
          value_template: >
            {{ receiver_current_source != receiver_target_source }}
      sequence:
        - service: media_player.turn_on
          entity_id: !input receiver
        - service: media_player.select_source
          entity_id: !input receiver
          data:
            source: !input receiver_source
        - delay:
            milliseconds: !input sync_volume_buffer_time
        - service: media_player.volume_set
          entity_id: !input receiver
          data:
            volume_level: >
              {{ sonos_current_volume }}

    - alias: "Turn off receiver"
      conditions:
        - condition: trigger
          id: sonos_paused
        - condition: template
          value_template: >
            {{ auto_turn_off and receiver_current_source == receiver_target_source }}
      sequence:
        - service: media_player.turn_off
          entity_id: !input receiver

    - alias: "Switch Sonos playing state"
      conditions:
        - condition: trigger
          id: receiver_source_changed
      sequence:
        - service: media_player.media_pause
          entity_id: !input sonos_connect

    - alias: "Change receiver volume"
      conditions:
        - condition: trigger
          id: sonos_volume
        - condition: template
          value_template: >
            {{ sync_volume }}
        - condition: template
          value_template: >
            {{ receiver_current_source == receiver_target_source }}
        - condition: template
          value_template: >
            {{ trigger.to_state.attributes["volume_level"] != receiver_current_volume }}
      sequence:
        - service: media_player.volume_set
          entity_id: !input receiver
          data:
            volume_level: >
              {{ trigger.to_state.attributes["volume_level"] }}

    - alias: "Change Sonos volume"
      conditions:
        - condition: trigger
          id: receiver_volume
        - condition: template
          value_template: >
            {{ sync_volume }}
        - condition: template
          value_template: >
            {{ receiver_current_source == receiver_target_source }}
        - condition: template
          value_template: >
            {{ trigger.to_state.attributes["volume_level"] != sonos_current_volume }}
      sequence:
        - service: media_player.volume_set
          entity_id: !input sonos_connect
          data:
            volume_level: >
              {{ trigger.to_state.attributes["volume_level"] }}
